baseURL = 'https://solairerove.github.io/'
languageCode = 'en-us'
title = 'Headstone lamp - leetcode grind (60)'
theme="archie"
copyright = "© solairerove"

# Code Highlight
pygmentsstyle = "emacs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=4 # articles per page

[params]
mode="auto" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
mathjax = false # enable MathJax support
katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/solairerove"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
